import com.modrinth.minotaur.dependencies.ModDependency

architectury {
    platformSetupLoomIde()
    fabric()
}


configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    shadowCommon {
        canBeResolved = true
        canBeConsumed = false
    }
    apiElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
    runtimeElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
}

repositories {
    maven {
        name "ModMenu Maven"
        url "https://maven.terraformersmc.com/releases/"
    }
    maven { url "https://maven.shedaniel.me/" }
}

loom {
    mixin {
        defaultRefmapName = "mixins.${archives_name}_fabric.refmap.json"
    }
}

dependencies {
    api "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    api fabricApi.module("fabric-resource-loader-v0", rootProject.fabric_api_version)
    api("me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }
    compileOnly "com.terraformersmc:modmenu:${rootProject.modmenu_version}"
    common(project(path: ":common")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive false }
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

afterEvaluate {
    loom.runs.configureEach {
        vmArg "-javaagent:${configurations.compileClasspath.find { it.name.contains("sponge-mixin") }}"
    }
}

String fileName = "showkeybinds-${project.version}"

List<String> devExcludes = ["architectury.common.json"]

sourcesJar {
    Jar commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
    excludes = devExcludes
}

jar {
    archiveClassifier = "raw"
}

shadowJar {
    dependsOn(jar)
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "fabric"
    from rootProject.file("LICENSE.md")
    archiveVersion = "v${mod_version}"
    archiveBaseName = fileName
}

curseforge {
    apiKey = project.hasProperty("curseforge_api_token") ? curseforge_api_token : ""
    project {
        id = "684957"
        changelog = rootProject.file("CHANGE_LOG.md")
        changelogType = "markdown"
        releaseType = "release"
        addGameVersion "Fabric"
        addGameVersion minecraft_version
        addGameVersion "Java 25"
        mainArtifact shadowJar.archiveFile
        afterEvaluate {
            uploadTask.dependsOn(shadowJar)
        }
    }
    options {
        forgeGradleIntegration = false
    }
}

modrinth {
    token = project.hasProperty("modrinth_api_token") ? modrinth_api_token : ""
    projectId = "zaElPFa3"
    versionName = "Show Keybinds ${rootProject.mod_version} ${minecraft_version} Fabric"
    versionNumber = "showkeybinds-" + rootProject.mod_version
    uploadFile = shadowJar
    changelog = rootProject.file("CHANGE_LOG.md").text
    gameVersions = ["${minecraft_version}"]
    loaders = ["fabric"]
    dependencies = [new ModDependency('mOgUt4GM', 'optional'),
                    new ModDependency('9s6osm5g', 'required')]
}
