# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=4.1.2
maven_group=com.sjkz1
archives_name=showkeybinds
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21.1
# Dependencies
architectury_api_version=13.0.8
fabric_loader_version=0.16.10
fabric_api_version=0.115.0+1.21.1
neoforge_version=21.1.120
cloth_config_version=15.0.140
modmenu_version=11.0.3
