# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=26.1.2.1
maven_group=com.sjkz1
archives_name=showkeybinds
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=26.1.2
# Dependencies
fabric_loader_version=0.19.2
fabric_api_version=0.147.0+26.1.2
neoforge_version=26.1.2.30-beta
cloth_config_version=26.1.154
modmenu_version=18.0.0-alpha.8
