architectury {
    common enabled_platforms.split(',')
}

tasks.shadowJar {
    zip64 = true
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$fabric_loader_version"
    modImplementation "dev.architectury:architectury:$architectury_api_version"
    modImplementation("me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}") {
        exclude(group: "net.fabricmc.fabric-api")
        exclude(group: "net.fabricmc", module: "fabric-loader")
    }
}

loom {
    mixin {
        defaultRefmapName = "mixins.${archives_name}.refmap.json"
    }
}
