modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "showkeybinds"
version = "${version}"
displayName = "Show Keybinds"
logoFile = "logo.png"
authors = "SJKZ1"
description = '''
Show key binding on Hotbar and Inventory!
'''
#logoFile = ""

[[dependencies.showkeybinds]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.showkeybinds]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.showkeybinds]]
modId = "architectury"
type = "required"
versionRange = "[19.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "showkeybinds.mixins.json"
